### ISSUE TITLE
What to put in the cookies variables?

### ISSUE THREAD

**Issue by lucasbezer** [lpsm-dev/auto-earn-bybot#7]
What to put in the COOKIES_AUTH_ASPXAUTH and COOKIES_AUTH_ASPXROLES variables and how to collect them?

**Comment by lpsm-dev** [comment]
You need these variables to make HTTP requests. To collect them, just log in to bybot, inspect the page in developer mode and detail an internal request.

Limitations: every 2 days you need to change this variables

**Comment by lpsm-dev** [comment]
Actually, you only need the `COOKIES_AUTH_ASPXAUTH` variable. Recently they updated the website and the other variable was removed
